# Generated by Django 3.0 on 2021-07-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remind',
            old_name='reminder',
            new_name='remind',
        ),
    ]
